name= input ("What is you name?")

birth1=input("Please enter your birthday:")
name2= input ("What is you name?")
birth2=input("Please enter your birthday:")
name3 = input ("What is you name?")
birth3=input("Please enter your birthday:")
name4 = input ("What is you name?")
birth4=input("Please enter your birthday:")
name5= input ("What is you name?")
birth5=input("Please enter your birthday:")
print(f"Hello {name} your birthday is on {birth1}")
print(f"Hello {name2} your birthday is on {birth2}")
print(f"Hello {name3} your birthday is on {birth3}")
print(f"Hello {name4} your birthday is on {birth4}")
print(f"Hello {name5} your birthday is on {birth5}")